name: Build Flutter APK
on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # Updated to include Dart SDK 3.5.0+

      - name: Install Dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release --shrink --obfuscate --split-debug-info=build/debug-info --split-per-abi
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: watameal-release-apks
          path: build/app/outputs/flutter-apk/*.apk  # Fixed path
